{{- with .Values.secrets.generic }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vector.fullname" $ }}
  labels:
    {{- include "vector.labels" $ | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := $.Values.secrets.generic }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}

{{- with .Values.secrets.tls }}
{{- range $name, $attrs := $.Values.secrets.tls }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vector.fullname" $ }}-{{ $key }}
  labels:
    {{- include "vector.labels" $ | nindent 4 }}
type: kubernetes.io/tls
data:
{{- range $key, $value := $attrs }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
